//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input/GridInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GridInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GridInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GridInput"",
    ""maps"": [
        {
            ""name"": ""GridActions"",
            ""id"": ""75f8fb06-7d83-45b4-a6ea-8b1f6aa9abb6"",
            ""actions"": [
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a173fd64-c234-4cbb-9a54-db8a291565c6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""b4d775ba-9e30-43bc-a759-a90e19ab3dc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""a5134a9c-0849-4934-95f2-a0f776ebc838"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4cb0bcf1-7e1f-4348-9e4a-df5c5ec7fa82"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02bb2b3d-c095-4a55-856e-b9cf8abbc39d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2511efb-d763-4d56-8ed1-8bc0e863743f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GridActions
        m_GridActions = asset.FindActionMap("GridActions", throwIfNotFound: true);
        m_GridActions_MousePosition = m_GridActions.FindAction("MousePosition", throwIfNotFound: true);
        m_GridActions_MouseClick = m_GridActions.FindAction("MouseClick", throwIfNotFound: true);
        m_GridActions_Rotate = m_GridActions.FindAction("Rotate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GridActions
    private readonly InputActionMap m_GridActions;
    private List<IGridActionsActions> m_GridActionsActionsCallbackInterfaces = new List<IGridActionsActions>();
    private readonly InputAction m_GridActions_MousePosition;
    private readonly InputAction m_GridActions_MouseClick;
    private readonly InputAction m_GridActions_Rotate;
    public struct GridActionsActions
    {
        private @GridInput m_Wrapper;
        public GridActionsActions(@GridInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @MousePosition => m_Wrapper.m_GridActions_MousePosition;
        public InputAction @MouseClick => m_Wrapper.m_GridActions_MouseClick;
        public InputAction @Rotate => m_Wrapper.m_GridActions_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_GridActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GridActionsActions set) { return set.Get(); }
        public void AddCallbacks(IGridActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_GridActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GridActionsActionsCallbackInterfaces.Add(instance);
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @MouseClick.started += instance.OnMouseClick;
            @MouseClick.performed += instance.OnMouseClick;
            @MouseClick.canceled += instance.OnMouseClick;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
        }

        private void UnregisterCallbacks(IGridActionsActions instance)
        {
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @MouseClick.started -= instance.OnMouseClick;
            @MouseClick.performed -= instance.OnMouseClick;
            @MouseClick.canceled -= instance.OnMouseClick;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
        }

        public void RemoveCallbacks(IGridActionsActions instance)
        {
            if (m_Wrapper.m_GridActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGridActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_GridActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GridActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GridActionsActions @GridActions => new GridActionsActions(this);
    public interface IGridActionsActions
    {
        void OnMousePosition(InputAction.CallbackContext context);
        void OnMouseClick(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
}
